name: Deploy to Production

on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          
      - name: Install dependencies
        run: |
          npm install

      - name: Run tests
        run: |
          npm run test --if-present

      - name: Build project
        run: |
          npm run build

      - name: Zip build directory
        run: |
          zip build.zip ./* -r
        shell: bash

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: build.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: 
      name: 'Production'
      url: ${{ steps.delpoy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip build.zip

      - name: 'Deploy to Azure Web App Staging'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'checkmed-in'
          slot-name: 'Production'
          publish-profile: ${{ secrets.PROD }}
          package: .