name: Deploy to UAT

on:
  push:
    branches:
      - prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          
      - name: Install dependencies
        run: |
          npm install

      - name: Run tests
        run: |
          npm run test --if-present

      - name: Build project
        run: |
          npm run build

      - name: Zip build directory
        run: |
          zip -r build.zip .next
        shell: bash

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: build.zip

  deploy-staging:
    runs-on: ubuntu-latest
    needs: build
    environment: 'Staging'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip build.zip -d ./deploy

      - name: List files in artifact
        run: ls -la ./deploy/.next

      - name: 'Deploy to Azure Web App Staging'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'checkmed-UAT'
          package: ./deploy/.next
          publish-profile: ${{ secrets.PRODUCTION_CRED }}

  deploy-production:
    runs-on: ubuntu-latest
    needs: deploy-staging
    environment: 'Production'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip build.zip -d ./deploy

      - name: List files in artifact
        run: ls -la ./deploy/.next

      - name: 'Deploy to Azure Web App Production'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'checkmed-UAT'
          package: ./deploy/.next
          publish-profile: ${{ secrets.PRODUCTION_CRED }}